// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: human/observe_vote.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ObserveVote struct {
	Index   string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Creator string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Txhash  string `protobuf:"bytes,3,opt,name=txhash,proto3" json:"txhash,omitempty"`
	From    string `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To      string `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	Amount  string `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Txtime  string `protobuf:"bytes,7,opt,name=txtime,proto3" json:"txtime,omitempty"`
	ChainId string `protobuf:"bytes,8,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Used    string `protobuf:"bytes,9,opt,name=used,proto3" json:"used,omitempty"`
}

func (m *ObserveVote) Reset()         { *m = ObserveVote{} }
func (m *ObserveVote) String() string { return proto.CompactTextString(m) }
func (*ObserveVote) ProtoMessage()    {}
func (*ObserveVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_70539d84b3e52c6a, []int{0}
}
func (m *ObserveVote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ObserveVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ObserveVote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ObserveVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObserveVote.Merge(m, src)
}
func (m *ObserveVote) XXX_Size() int {
	return m.Size()
}
func (m *ObserveVote) XXX_DiscardUnknown() {
	xxx_messageInfo_ObserveVote.DiscardUnknown(m)
}

var xxx_messageInfo_ObserveVote proto.InternalMessageInfo

func (m *ObserveVote) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ObserveVote) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ObserveVote) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

func (m *ObserveVote) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ObserveVote) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ObserveVote) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *ObserveVote) GetTxtime() string {
	if m != nil {
		return m.Txtime
	}
	return ""
}

func (m *ObserveVote) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *ObserveVote) GetUsed() string {
	if m != nil {
		return m.Used
	}
	return ""
}

func init() {
	proto.RegisterType((*ObserveVote)(nil), "human.human.ObserveVote")
}

func init() { proto.RegisterFile("human/observe_vote.proto", fileDescriptor_70539d84b3e52c6a) }

var fileDescriptor_70539d84b3e52c6a = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0xe3, 0xd0, 0xa6, 0xd4, 0x95, 0x18, 0x0c, 0x42, 0x37, 0x59, 0x88, 0x89, 0x85, 0x76,
	0xe0, 0x0d, 0xd8, 0x98, 0x90, 0x18, 0x18, 0x58, 0x90, 0x4b, 0x0e, 0x25, 0x43, 0x72, 0x95, 0x73,
	0xa9, 0xc2, 0x5b, 0xf0, 0x58, 0x8c, 0xdd, 0x60, 0x44, 0xc9, 0x8b, 0x54, 0xb9, 0x6b, 0x16, 0xfb,
	0x7e, 0xdf, 0xfd, 0xd5, 0x67, 0xa1, 0x68, 0xab, 0x50, 0x6f, 0x68, 0xdb, 0x60, 0xdc, 0xe3, 0xfb,
	0x9e, 0x18, 0xd7, 0xbb, 0x48, 0x4c, 0x6e, 0x25, 0x99, 0xb5, 0xbc, 0xb7, 0xbf, 0xc6, 0xae, 0x9e,
	0xb5, 0xe6, 0x95, 0x18, 0xdd, 0x95, 0x9d, 0x97, 0x75, 0x8e, 0x1d, 0x98, 0x1b, 0x73, 0xb7, 0x7c,
	0x51, 0x70, 0x60, 0x17, 0x1f, 0x11, 0x03, 0x53, 0x84, 0x54, 0xf4, 0x09, 0xdd, 0xb5, 0xcd, 0xb8,
	0x2b, 0x42, 0x53, 0xc0, 0x99, 0x24, 0x4e, 0xe4, 0x9c, 0x9d, 0x7d, 0x46, 0xaa, 0x60, 0x26, 0xaa,
	0xc4, 0xee, 0xc2, 0xa6, 0x4c, 0x30, 0x17, 0x25, 0x65, 0x1a, 0x7b, 0x43, 0x45, 0x6d, 0xcd, 0x90,
	0x69, 0xaf, 0x92, 0xce, 0xe4, 0xb2, 0x42, 0x58, 0x4c, 0x33, 0x47, 0x92, 0x2b, 0x8a, 0x50, 0xd6,
	0x4f, 0x39, 0x9c, 0x9f, 0xae, 0x50, 0x1c, 0xb7, 0xb5, 0x0d, 0xe6, 0xb0, 0xd4, 0x6d, 0x63, 0xfc,
	0x78, 0xff, 0xd3, 0x7b, 0x73, 0xe8, 0xbd, 0xf9, 0xef, 0xbd, 0xf9, 0x1e, 0x7c, 0x72, 0x18, 0x7c,
	0xf2, 0x37, 0xf8, 0xe4, 0xed, 0x52, 0xad, 0xe9, 0x36, 0xfa, 0xf3, 0xd7, 0x0e, 0x9b, 0x6d, 0x26,
	0xe6, 0x3c, 0x1c, 0x03, 0x00, 0x00, 0xff, 0xff, 0xda, 0x9e, 0x5a, 0x13, 0x38, 0x01, 0x00, 0x00,
}

func (m *ObserveVote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ObserveVote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ObserveVote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Used) > 0 {
		i -= len(m.Used)
		copy(dAtA[i:], m.Used)
		i = encodeVarintObserveVote(dAtA, i, uint64(len(m.Used)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintObserveVote(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Txtime) > 0 {
		i -= len(m.Txtime)
		copy(dAtA[i:], m.Txtime)
		i = encodeVarintObserveVote(dAtA, i, uint64(len(m.Txtime)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintObserveVote(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.To) > 0 {
		i -= len(m.To)
		copy(dAtA[i:], m.To)
		i = encodeVarintObserveVote(dAtA, i, uint64(len(m.To)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintObserveVote(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Txhash) > 0 {
		i -= len(m.Txhash)
		copy(dAtA[i:], m.Txhash)
		i = encodeVarintObserveVote(dAtA, i, uint64(len(m.Txhash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintObserveVote(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintObserveVote(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintObserveVote(dAtA []byte, offset int, v uint64) int {
	offset -= sovObserveVote(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ObserveVote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovObserveVote(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovObserveVote(uint64(l))
	}
	l = len(m.Txhash)
	if l > 0 {
		n += 1 + l + sovObserveVote(uint64(l))
	}
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovObserveVote(uint64(l))
	}
	l = len(m.To)
	if l > 0 {
		n += 1 + l + sovObserveVote(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovObserveVote(uint64(l))
	}
	l = len(m.Txtime)
	if l > 0 {
		n += 1 + l + sovObserveVote(uint64(l))
	}
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovObserveVote(uint64(l))
	}
	l = len(m.Used)
	if l > 0 {
		n += 1 + l + sovObserveVote(uint64(l))
	}
	return n
}

func sovObserveVote(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozObserveVote(x uint64) (n int) {
	return sovObserveVote(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ObserveVote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowObserveVote
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ObserveVote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ObserveVote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObserveVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthObserveVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthObserveVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObserveVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthObserveVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthObserveVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Txhash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObserveVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthObserveVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthObserveVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Txhash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObserveVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthObserveVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthObserveVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObserveVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthObserveVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthObserveVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.To = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObserveVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthObserveVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthObserveVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Txtime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObserveVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthObserveVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthObserveVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Txtime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObserveVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthObserveVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthObserveVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Used", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowObserveVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthObserveVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthObserveVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Used = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipObserveVote(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthObserveVote
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipObserveVote(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowObserveVote
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowObserveVote
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowObserveVote
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthObserveVote
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupObserveVote
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthObserveVote
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthObserveVote        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowObserveVote          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupObserveVote = fmt.Errorf("proto: unexpected end of group")
)
